package glenn.gasesframework.common;

import glenn.gasesframework.api.GasesFrameworkAPI;
import glenn.moddingutils.Configurations;

import java.io.File;

import net.minecraft.block.Block;
import net.minecraft.item.Item;

public class GasesFrameworkMainConfigurations extends Configurations
{
	@ConfigField(path="worldgen.Retrogen.Enable", comment="If true, retrogen will be enabled for only the next Minecraft session. This field will automatically reset to its default value. Consult the information database for more information", defaultValue="false", autoReset=true)
	public boolean retrogenEnabled;
	
	@ConfigField(path="gases.Smoke.Fire smoke amount", comment="The amount of smoke that will be generated by fire from 0 to 16", defaultValue="8")
	public int gases_fireSmokeAmount;
	
	@ConfigField(path="gases.Gas explosion factor", comment="The power of gas explosions", defaultValue="2.5")
	public float gases_gasExplosionFactor;

	@ConfigField(path="gases.Max gas height", comment="The maximal height gas can reach before it disappears", defaultValue="256")
	public int gases_maxGasHeight;

	@ConfigField(path="gases.Additional ignition blocks", comment="A list of block names for blocks that will be added to the gas ignition block registry", defaultValue="")
	public String[] other_additionalIgnitionBlocks;

	@ConfigField(path="gases.Removed ignition blocks", comment="A list of block names for blocks that will be removed from the gas ignition block registry", defaultValue="")
	public String[] other_removedIgnitionBlocks;

	@ConfigField(path="gases.Additional ignition items", comment="A list of item names for items that will be added to the gas ignition item registry", defaultValue="")
	public String[] other_additionalIgnitionItems;

	@ConfigField(path="gases.Removed ignition items", comment="A list of item names for items that will be removed from the gas ignition item registry", defaultValue="")
	public String[] other_removedIgnitionItems;
	
	@ConfigField(path="blocks.Gas furnace.Heating speed", comment="The speed at which gas furnaces heat up and cool down", defaultValue="2")
	public int other_gasFurnaceHeatingSpeed;
	
	@ConfigField(path="blocks.Gas tank.Fancy tanks", comment="Whether or not gas tanks will be rendered with fancy fluid physics", defaultValue="true")
	public boolean other_fancyTank;

	@ConfigField(path="blocks.Gas Dynamo.Max fuel", comment="The maximal amount of fuel contained by a gas dynamo", defaultValue="1000")
	public int gasDynamo_maxFuel;
	
	@ConfigField(path="blocks.Gas Dynamo.Fuel per tick", comment="The maximal amount of fuel consumed per tick by a gas dynamo", defaultValue="4")
	public int gasDynamo_fuelPerTick;
	
	@ConfigField(path="blocks.Gas Dynamo.RF per fuel", comment="The RF (Redstone Flux) generated per unit of fuel", defaultValue="16")
	public int gasDynamo_energyPerFuel;
	
	@ConfigField(path="blocks.Gas Dynamo.Max RF", comment="The maximal amount of RF (Redstone Flux) contained by a gas dynamo", defaultValue="60000")
	public int gasDynamo_maxEnergy;
	
	@ConfigField(path="blocks.Gas Dynamo.Max RF transfer", comment="The maximal amount of RF (Redstone Flux) that can be evently transmitted from a gas dynamo each tick", defaultValue="80")
	public int gasDynamo_maxEnergyTransfer;
	
	@ConfigField(path="piping.Iron material.Max pressure", comment="The maximal amount of pressure piping blocks of the iron tier can produce", defaultValue="31")
	public int piping_iron_maxPressure;

	@ConfigField(path="piping.Iron material.Pipe pressure tolerance", comment="The amount of pressure iron pipes can take before breaking", defaultValue="31")
	public int piping_iron_pressureTolerance;

	@ConfigField(path="piping.Glass material.Pipe pressure tolerance", comment="The amount of pressure glass pipes can take before breaking", defaultValue="31")
	public int piping_glass_pressureTolerance;
	
	@ConfigField(path="piping.Wood material.Max pressure", comment="The maximal amount of pressure piping blocks of the wood tier can produce", defaultValue="7")
	public int piping_wood_maxPressure;

	@ConfigField(path="piping.Wood material.Pipe pressure tolerance", comment="The amount of pressure wood pipes can take before breaking", defaultValue="7")
	public int piping_wood_pressureTolerance;

	@ConfigField(path="updatechecker.Enable", comment="Allow Gases Framework to automatically check for updates", defaultValue="true")
	public boolean other_enableUpdateCheck;
	
	public GasesFrameworkMainConfigurations(File configurationsFile)
	{
		super(configurationsFile);
	}

	@Override
	protected void onLoaded()
	{
		
	}
}